name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ['main'] # триггер при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # или любая нужная версия Node.js

      # 3. Устанавливаем зависимости через npm
      - name: Install dependencies
        run: npm ci

      # 4. Сборка проекта
      - name: deploy to gh
        run: npm run build

      # 5. Деплой на ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # ветка для билда
          publish_dir: ./Frontend/dist # папка сборки Vite
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
          force_orphan: true # создаёт ветку с нуля
